"""Audit recorded WafrCash openings per customer and ASIN on 2026-09-26.

Run on Railway with a WafrCash SQLite database:
    python wafrcash_day26_customer_asin_opens.py

Optionally reuse an existing audit JSON with --audit /path/to/audit.json.

This is a hypothetical pricing experiment, not Amazon's actual attribution.
One golden question stores its first link opening, not repeated taps on that
same question. Each (customer, ASIN) counts as at most one priced click here.
"""

import argparse
import csv
import json
import os
import sqlite3
from collections import Counter, defaultdict
from decimal import Decimal
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo


# Advertised EPC in the WafrCash report for 26 September; not earned Amazon EPC.
ADVERTISED_EPC = {
    "B0017IMON0": "22", "B07FNY8RPR": "8.54", "B0854HDBYB": "22",
    "B085XMNWQ8": "15", "B08R9YL1M3": "22", "B08R9ZB2LZ": "22",
    "B08WJMZM7W": "9.81", "B08WJPZJFH": "8", "B08Z42WY7T": "8",
    "B09RG7YVFT": "8.84", "B09RQX8SPN": "19.05", "B09VFKCY35": "22",
    "B0B2DPPLMW": "0.30", "B0BF591PWJ": "22", "B0BF5C2S2Y": "22",
    "B0BVZYZYX5": "22",
}
PENNY = Decimal("0.01")


def database_path():
    if os.getenv("DATABASE_PATH"):
        return os.environ["DATABASE_PATH"]
    try:
        import config
        return getattr(config, "DATABASE_PATH", None)
    except ImportError:
        return None


def customers_from_database(path, requested_day, parser):
    db = Path(path).resolve()
    if not db.is_file():
        parser.error(f"SQLite database not found: {db}")
    start = datetime.combine(date.fromisoformat(requested_day), datetime.min.time(),
                             ZoneInfo("Africa/Cairo"))
    end = start + timedelta(days=1)
    begin_utc, end_utc = [t.astimezone(timezone.utc).replace(tzinfo=None).isoformat()
                          for t in (start, end)]
    try:
        with sqlite3.connect(db.as_uri() + "?mode=ro", uri=True) as conn:
            rows = conn.execute("""SELECT user_id, UPPER(asin), COUNT(*)
                                   FROM golden_questions
                                   WHERE link_opened_at IS NOT NULL
                                     AND datetime(link_opened_at) >= datetime(?)
                                     AND datetime(link_opened_at) < datetime(?)
                                   GROUP BY user_id, UPPER(asin)
                                   ORDER BY user_id, UPPER(asin)""", (begin_utc, end_utc)).fetchall()
    except sqlite3.Error as exc:
        parser.error(f"Could not read golden_questions in {db}: {exc}")
    return [(int(uid), asin or "(unknown)", int(count)) for uid, asin, count in rows]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit", help="Optional JSON generated by wafrcash_click_audit.py")
    parser.add_argument("--db", default=database_path(),
                        help="WafrCash SQLite file; defaults to DATABASE_PATH in the environment or config.py")
    parser.add_argument("--day", default="2026-09-26")
    parser.add_argument("--out", default="wafrcash_day26_customer_asin_opens.csv")
    parser.add_argument("--only-repeated", action="store_true",
                        help="Print only repeated customer/ASIN pairs; CSV always includes all")
    args = parser.parse_args()

    if args.audit:
        audit_path = Path(args.audit)
        if not audit_path.is_file():
            parser.error(f"Audit JSON not found: {audit_path}")
        data = json.loads(audit_path.read_text(encoding="utf-8"))
        day = next((d for d in data["days"] if d["date_cairo"] == args.day), None)
        if day is None:
            parser.error(f"Date {args.day} is not present in {args.audit}")
        entries = [(customer["user_id"], asin.upper(), int(count))
                   for customer in day["customers"]
                   for asin, count in customer["asins"].items() if int(count) > 0]
    else:
        if not args.db:
            parser.error("Database path missing: use --db /app/<database>.db or set DATABASE_PATH")
        entries = customers_from_database(args.db, args.day, parser)

    products = defaultdict(lambda: {"customers": 0, "opens": 0, "repeat_customers": 0})
    for uid, asin, count in entries:
        p = products[asin]
        p["customers"] += 1
        p["opens"] += count
        p["repeat_customers"] += count > 1

    entries.sort(key=lambda row: (row[0], row[1]))
    with Path(args.out).open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.writer(file)
        writer.writerow(["user_id", "asin", "recorded_opens", "repeated",
                         "advertised_epc_egp", "hypothetical_epc_if_customer_repeated_egp",
                         "hypothetical_epc_if_any_customer_repeated_egp"])
        for uid, asin, count in entries:
            epc = ADVERTISED_EPC.get(asin)
            writer.writerow([uid, asin, count, "yes" if count > 1 else "no", epc or "",
                             "0.01" if count > 1 else (epc or ""),
                             "0.01" if products[asin]["repeat_customers"] else (epc or "")])

    for uid, asin, count in entries:
        if not args.only_repeated or count > 1:
            print(f"customer={uid}  asin={asin}  opened={count}"
                  + ("  REPEATED" if count > 1 else ""))

    print("\nProduct summary (hypothetical, one priced click per customer/ASIN):")
    by_customer_total = Decimal("0")
    whole_product_total = Decimal("0")
    for asin, p in sorted(products.items(), key=lambda pair: (-pair[1]["opens"], pair[0])):
        epc = ADVERTISED_EPC.get(asin)
        print(f"{asin}: opens={p['opens']}  customers={p['customers']}  "
              f"repeat_customers={p['repeat_customers']}  "
              f"whole_product_at_0.01={'yes' if p['repeat_customers'] else 'no'}")
        if epc is not None:
            by_customer_total += (p["customers"] - p["repeat_customers"]) * Decimal(epc)
            by_customer_total += p["repeat_customers"] * PENNY
            whole_product_total += p["customers"] * (PENNY if p["repeat_customers"] else Decimal(epc))

    missing = sorted(set(products) - set(ADVERTISED_EPC))
    if missing:
        print("No advertised EPC for:", ", ".join(missing), "(excluded from totals)")
    print(f"TOTAL customer/ASIN rows={len(entries)}  recorded opens={sum(p['opens'] for p in products.values())}  "
          f"repeated customer/ASIN pairs={sum(p['repeat_customers'] for p in products.values())}")
    print(f"Hypothetical total when ONLY repeated customers' products cost 0.01: {by_customer_total:.2f} EGP")
    print(f"Hypothetical total when ANY repeat makes ENTIRE ASIN cost 0.01: {whole_product_total:.2f} EGP")
    print(f"Saved: {Path(args.out).resolve()}")
    print("Opening the same question twice is recorded once; actual Amazon clicks and earnings are not in this JSON.")


if __name__ == "__main__":
    main()
